# Site settings
title: "Riedil Genova"
email: "info@riedilge.com"
description: >
  Riedil Genova, edilizia a Genova per tutte le tasche.
url: "http://riedilge.com/"
#url: "http://localhost:4000"

owner: "Riedil Genova"
email: "info@riedilge.com"
address:
  - line: "Via Cornigliano 14/5, 16152, Genova, GE, IT"
telephone: "+39 393 92 18 175"
copyright: "Riedil di Fucarese Lucia"

markdown: kramdown

sass:
    style: compressed

gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

paginate: 5
paginate_path: 'galleria/p:num'
